name: 'Gitbook Action Build'
on:
    push:
        branches:
            - master # trigger branch
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [8]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install_gitbook_plugins
              run: |
                  npm install gitbook-cli  -g
                  npm i gitbook@3.2.2
                  gitbook -v
                  gitbook install
            # - name: build_gitbook
            #   run: |
            #       gitbook build      
            # - name: commit
            #   run: |
            #       cd ./_book
            #       git init
            #       git config --local user.name "${GITHUB_ACTOR}"
            #       git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            #       git add *
            #       git commit -m "Update by gitbook-action"
            # - name: push
            #   uses: ad-m/github-push-action@master
            #   with:
            #     github_token: ${{ secrets.GITHUB_TOKEN }}
            #     branch:  gh-pages
            - name: install ebook-conver
              run: |
                   sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
            - name: build pdf book
              run: |
                  gitbook pdf . ~/book/kubernetes-handbook.pdf
            - name: commit pdf book
              run: |
                  cd ~/book/
                  git init
                  git config --local user.name "${GITHUB_ACTOR}"
                  git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
                  git add *
                  git commit -m "pdf book"
            - name: push pdf book
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: pdf-book             
